/// Generated by poinciana using BTT

#[test]
fn test_hashPair_should_never_revert() {
    // It should never revert.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_hashPair_when_first_arg_is_smaller_than_second_arg() {
    // It should match the result of `keccak256(abi.encodePacked(a,b))`.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_hashPair_when_first_arg_is_bigger_than_second_arg() {
    // It should match the result of `keccak256(abi.encodePacked(b,a))`.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_min_should_never_revert() {
    // It should never revert.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_min_when_first_arg_is_smaller_than_second_arg() {
    // It should match the value of `a`.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_min_when_first_arg_is_bigger_than_second_arg() {
    // It should match the value of `b`.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_max_should_never_revert() {
    // It should never revert.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_max_when_first_arg_is_smaller_than_second_arg() {
    // It should match the value of `b`.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_max_when_first_arg_is_bigger_than_second_arg() {
    // It should match the value of `a`.

    panic!("NOT IMPLEMENTED");
}

