/// Generated by poinciana using BTT

#[test]
fn test_function1_should_never_revert() {
    // It should never revert.

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_function1_when_first_arg_is_bigger_than_second_arg() {
    // It is all good

    panic!("NOT IMPLEMENTED");
}

#[test]
fn test_function2_when_stuff_happens() {
    // It should do something simple

    panic!("NOT IMPLEMENTED");
}

