/// Generated by poinciana using BTT

fn when_stuff_is_called() {// code
}

#[test]
fn test_panic_when_a_condition_is_met() {
    when_stuff_is_called();

    // It should revert.
    //     Because we shouldn't allow it.

    panic!("NOT IMPLEMENTED");
}

